// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poke.Server.Data.Match;

#nullable disable

namespace Poke.Server.Data.Match.Migrations
{
    [DbContext(typeof(MatchContext))]
    [Migration("20250528170308_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("match")
                .HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Poke.Server.Data.Match.Models.Match", b =>
                {
                    b.Property<Guid>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMatchOver")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team01ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Team02ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserID01")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserID02")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserWinnerID")
                        .HasColumnType("TEXT");

                    b.HasKey("MatchID");

                    b.ToTable("match_matches", "match");
                });
#pragma warning restore 612, 618
        }
    }
}
